version: 2
updates:
  - package-ecosystem: npm
    directory: /roomiesbs-frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /roomieSBS-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
